# Generated by Django 4.2.1 on 2023-06-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=40)),
                ('Productos', models.CharField(max_length=40)),
                ('ValorProducto', models.CharField(max_length=10)),
                ('FechaCompra', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=40)),
                ('Productos', models.CharField(max_length=40)),
                ('ValorProducto', models.CharField(max_length=10)),
                ('FechaCompra', models.CharField(max_length=18)),
            ],
        ),
    ]
