# Generated by Django 4.2.1 on 2023-06-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lavado_Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Agendar_Hora',
        ),
    ]
