# Generated by Django 4.2.1 on 2023-06-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lavado_Vehiculos', '0002_rename_registro_agendar_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=40)),
                ('Productos', models.CharField(max_length=40)),
                ('ValorProducto', models.CharField(max_length=10)),
                ('FechaCompra', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Lavado',
        ),
    ]
