# Generated by Django 4.2.3 on 2023-07-23 04:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Lavado_Vehiculos', '0003_servicios_delete_lavado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('bodeguero', 'Bodeguero')], default='cliente', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lavado_Vehiculos.customuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendar_hora',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='agendar_hora',
            name='FechaCompra',
        ),
        migrations.RemoveField(
            model_name='agendar_hora',
            name='Productos',
        ),
        migrations.RemoveField(
            model_name='agendar_hora',
            name='ValorProducto',
        ),
        migrations.AddField(
            model_name='agendar_hora',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='agendar_hora',
            name='fecha',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='agendar_hora',
            name='hora',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='agendar_hora',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='agendar_hora',
            name='placas',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='agendar_hora',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ListaFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturas', models.ManyToManyField(to='Lavado_Vehiculos.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lavado_Vehiculos.customuser')),
            ],
        ),
    ]
