# Generated by Django 4.2.3 on 2023-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lavado_Vehiculos', '0009_alter_agendar_hora_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendar_hora',
            name='fecha',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
